1.21.4
pavatus/ait pull request #785
Opened 2024-12-18 21:48 UTC by MaketendoDev

we'll continuously update this with 1.20.1 (DONT MERGE)

2024-12-18 21:50 UTC, Duzos commented
you can convert it to a draft in the top right

2024-12-18 21:51 UTC, MaketendoDev commented
1.20.1 and 1.21.4 isn't too big of a difference its just mostly item updates and model changes so any commit should work

2024-12-18 21:56 UTC, MaketendoDev commented
Like loqor said theo can do all the work

2024-12-18 21:57 UTC, MaketendoDev commented
if we have some kind of item conversion system it should update automatically the item stuff

2024-12-21 11:45 UTC, DrTheodor commented
> Like loqor said theo can do all the work 

what.

2024-12-21 11:46 UTC, DrTheodor requested changes
uh
I guess that's not finished

2024-12-21 11:46 UTC, DrTheodor commented on src/main/java/loqor/ait/core/AITItems.java
> +public class AITItems implements AutoRegistryContainer<BlockEntityType<?>> {
I dont think... thats right..?

2024-12-21 12:15 UTC, MaketendoDev commented
nah it isn't tbf i just pushed what i have so loqor can do some things

2024-12-21 12:16 UTC, MaketendoDev commented
its just stale fn until we have a update focused on this

2024-12-21 12:16 UTC, MaketendoDev commented on src/main/java/loqor/ait/core/AITItems.java
> +public class AITItems implements AutoRegistryContainer<BlockEntityType<?>> {
me testing around

2025-01-26 12:05 UTC, closed without merging